<a href="https://colab.research.google.com/github/pooniavaibhav/pytorchBasics/blob/main/NumpyBridge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 import numpy as np
 import torch

In [3]:
#converting a torch tensor to a numpy array-
torch_array = torch.ones(5)
numpy_array = torch_array.numpy()
print(numpy_array)
print(type(numpy_array))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [4]:
# now make a change in the torch_array-
# You will see a change in the numpy_array also this is called numpy bridge. 
torch_array.add_(1)
print(torch_array)
print(numpy_array)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [5]:
# converting the Numpy array to Torch tensor-
# see how changing the np array changed the torch tensor automatically-
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [6]:
# move a tensor to the GPU-
torch_array = torch.ones(5)
torch_array = torch_array.cuda()
print(torch_array)

tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [8]:
# Provide easy switching between CPU and GPU
add_result = torch.ones(5)
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
  add_result = add_result.cuda()
  print(add_result)

True
tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [9]:
#converting a list to tensor-
d = [2,3,4,6]
print(d)
to_list = torch.tensor(d)
print(to_list,to_list.dtype)

[2, 3, 4, 6]
tensor([2, 3, 4, 6]) torch.int64


# Tensor Concatenation

In [12]:
# Tensor Concatenation
first_1 = torch.randn(2,5)
print(first_1)
second_1 = torch.randn(3,5)
print(second_1)
# Concatinating along the 0 dimension (concatenate rows) -
print('\n')
con_1 = torch.cat([first_1, second_1])
print(con_1)
print('\n')

tensor([[ 1.0138,  0.5105,  0.4978, -0.6573, -1.5382],
        [ 0.8860, -0.9342,  0.5312, -0.8742, -0.0811]])
tensor([[ 0.1026, -0.2829,  0.8216, -1.7967,  0.4410],
        [-0.2245, -1.9092, -0.7891,  0.3581, -1.7591],
        [ 0.1051,  0.2076,  0.4728,  1.1694,  1.6555]])


tensor([[ 1.0138,  0.5105,  0.4978, -0.6573, -1.5382],
        [ 0.8860, -0.9342,  0.5312, -0.8742, -0.0811],
        [ 0.1026, -0.2829,  0.8216, -1.7967,  0.4410],
        [-0.2245, -1.9092, -0.7891,  0.3581, -1.7591],
        [ 0.1051,  0.2076,  0.4728,  1.1694,  1.6555]])




In [15]:
# concatinate along the 1 dimension (concatinate columns)-
first_2 = torch.randn(2,3)
print(first_2)
second_2 = torch.randn(2,5)
print(second_2)
con2 = torch.cat([first_2, second_2], 1)
print(con2)

tensor([[ 1.4578,  0.4513,  0.3705],
        [-1.5089, -0.1307,  0.2230]])
tensor([[ 1.7642,  0.4943,  0.4572, -0.1562, -0.0736],
        [ 0.2933,  0.5049, -0.0484,  1.0417,  0.8421]])
tensor([[ 1.4578,  0.4513,  0.3705,  1.7642,  0.4943,  0.4572, -0.1562, -0.0736],
        [-1.5089, -0.1307,  0.2230,  0.2933,  0.5049, -0.0484,  1.0417,  0.8421]])


## Adding dimensions to the tensor

In [18]:
# unsqueeze adds a dimension along the specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_2 = torch.unsqueeze(tensor_1,0)
print(tensor_2)
print(tensor_2.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [19]:
# for 3d columns-
tensor_3 = torch.rand(2,3,4)
print(tensor_3)
print('\n')
tensor_4 = tensor_3[:,:,2]
print(tensor_4)
print(tensor_4.shape)
tensor_5 = torch.unsqueeze(tensor_4,2)
print(tensor_5)

tensor([[[0.9574, 0.5491, 0.6166, 0.6968],
         [0.5462, 0.6364, 0.9293, 0.9389],
         [0.9945, 0.3434, 0.0793, 0.6724]],

        [[0.5582, 0.2103, 0.3637, 0.0438],
         [0.5426, 0.7920, 0.6254, 0.2832],
         [0.9391, 0.9574, 0.7440, 0.1947]]])


tensor([[0.6166, 0.9293, 0.0793],
        [0.3637, 0.6254, 0.7440]])
torch.Size([2, 3])
tensor([[[0.6166],
         [0.9293],
         [0.0793]],

        [[0.3637],
         [0.6254],
         [0.7440]]])
