<a href="https://colab.research.google.com/github/pooniavaibhav/pytorchBasics/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

## Torch Tensors

In [3]:
# this is a 1-D Array
a = torch.tensor([2,3,5,7])
print(a)

tensor([2, 3, 5, 7])


In [4]:
# 2-D tensor
b = torch.tensor([[2,4,5],[7,8,6],[2,7,9]])
print(b)

tensor([[2, 4, 5],
        [7, 8, 6],
        [2, 7, 9]])


In [5]:
# the size of tensors-
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([4])
torch.Size([3, 3])
torch.Size([4])
torch.Size([3, 3])


In [6]:
# get the number/height of tensor
print(b.shape[0])

3


In [17]:
 #To create a float tensor-
 #float is nothing but a method to represent very large or very small numbers  as an approximation to support a trade-off between range and precision.
float_tensor = torch.FloatTensor([[2,5,8],[6,8,9],[7,3,1]])
 # or 
float_tensor1 = torch.tensor([[1,3,4],[7,8,9],[1,4,7]],dtype=torch.float) 
print(c)
print(d.dtype)

tensor([[2., 5., 8.],
        [6., 8., 9.],
        [7., 3., 1.]])
torch.float32


In [16]:
#To create a double tensor-
# double is also a method to represent large or small numbers.Double is more precise and for storing large numbers, we prefer double over float. 
# Unless we do need precision up to 15 or 16 decimal points, we can stick to float in most applications, as double is more expensive
double_tensor = torch.DoubleTensor([[2,5,7],[1,2,6],[6,8,0]])
# or
double_tensor1 = torch.tensor([[1,3,4],[7,8,9],[1,4,7]],dtype=torch.double)
print(double_tensor)
print(double_tensor1.dtype)

tensor([[2., 5., 7.],
        [1., 2., 6.],
        [6., 8., 0.]], dtype=torch.float64)
torch.float64


In [19]:
#calculating the mean-
print(float_tensor1.mean())
print(double_tensor.mean())

tensor(4.8889)
tensor(4.1111, dtype=torch.float64)


In [20]:
# calculating the standard deviation-
print(float_tensor1.std())
print(double_tensor.std())

tensor(2.9768)
tensor(2.8916, dtype=torch.float64)


In [32]:
# Reshape the tensor-
# by providing the -1 python itself finds out the the number of rows-
print(b.view(-1,1))
#Yo can create a 1D array out of it-
print(b.view(9))
#shape into -1(rows times) * columns
print(b.view([-1,3]))
#shape into any times row * any times column-
print(b.view([9,1]))
#assign to a new shape
new_tensor = b.view([3,3])
print(new_tensor)

tensor([[2],
        [4],
        [5],
        [7],
        [8],
        [6],
        [2],
        [7],
        [9]])
tensor([2, 4, 5, 7, 8, 6, 2, 7, 9])
tensor([[2, 4, 5],
        [7, 8, 6],
        [2, 7, 9]])
tensor([[2],
        [4],
        [5],
        [7],
        [8],
        [6],
        [2],
        [7],
        [9]])
tensor([[2, 4, 5],
        [7, 8, 6],
        [2, 7, 9]])


In [35]:
#create a 3d tensor with channel,rows,columns
three_dim = torch.randn(2,3,4)
print(three_dim.view(2, 12))
print(three_dim.view(3,-1))

tensor([[ 0.7523,  0.2427, -0.6483, -1.4084, -0.0794,  0.3265,  1.1633,  0.3887,
          1.1742, -1.4552, -1.2554, -1.2419],
        [-0.2221, -1.1434,  1.0661,  0.0236,  1.1231,  0.3432, -1.7997,  0.7384,
          1.2868,  0.8411,  0.8247, -1.4260]])
tensor([[ 0.7523,  0.2427, -0.6483, -1.4084, -0.0794,  0.3265,  1.1633,  0.3887],
        [ 1.1742, -1.4552, -1.2554, -1.2419, -0.2221, -1.1434,  1.0661,  0.0236],
        [ 1.1231,  0.3432, -1.7997,  0.7384,  1.2868,  0.8411,  0.8247, -1.4260]])


In [38]:
## Create a matrix with random numbers between 0 and 1-
r = torch.rand(4,4)
print(r)

tensor([[0.8574, 0.9413, 0.2254, 0.3112],
        [0.9756, 0.4671, 0.8256, 0.1498],
        [0.6449, 0.6160, 0.7010, 0.3118],
        [0.9406, 0.3975, 0.3916, 0.3659]])


In [37]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1-
r1 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 3.6543e-01, -5.8744e-01,  1.3337e+00, -5.8298e-01],
        [ 7.7584e-01,  1.7143e-03, -1.3982e+00, -3.1969e-01],
        [-6.9047e-01,  4.1153e-01,  2.4750e+00, -4.4146e-01],
        [ 1.2173e+00,  2.8527e-01,  1.3485e+00,  1.0768e+00]])
torch.float32


In [39]:
# create an array of 5 random integers from values between 6 and 9(exclusive of 10)
int_array = torch.randint(6,9,(5,))
print(int_array)

tensor([6, 7, 8, 8, 6])


In [40]:
# create a 2D matrix of size 3*3 filled with random integers from values between 6 and 9-
int_array2 = torch.randint(6,10,(3,3))
print(int_array2)

tensor([[7, 7, 7],
        [6, 7, 6],
        [9, 9, 7]])


In [42]:
# get the number of elements in array-
print(torch.numel(int_array))
print(torch.numel(int_array2))

5
9


In [44]:
# construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3,3, dtype = torch.long)
print(z)
# construct a 3x3 matrix of ones-
o = torch.ones(3,3)
print(o)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [46]:
#creating a dtat set with random distribution similer and convert the data type of the tensor-
changed_data = torch.randn_like(r2, dtype=torch.double)
print(changed_data)

tensor([[ 0.4354,  0.6134, -1.4946,  0.6455],
        [-1.7036, -0.1491, -0.7472,  0.3916],
        [-0.2874,  1.1870,  1.8783,  1.5390],
        [-0.6244, -0.3841, -1.5049,  1.0582]], dtype=torch.float64)


In [47]:
# add two tensors,make sure they have the same size and the data type-
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 1.2228,  0.3539,  1.5591, -0.2718],
        [ 1.7514,  0.4688, -0.5726, -0.1699],
        [-0.0456,  1.0275,  3.1760, -0.1297],
        [ 2.1579,  0.6827,  1.7401,  1.4427]])


In [48]:
#In -place addition (change the value of r2 to th addition)
r2.add_(r)
print(r2)

tensor([[ 1.2228,  0.3539,  1.5591, -0.2718],
        [ 1.7514,  0.4688, -0.5726, -0.1699],
        [-0.0456,  1.0275,  3.1760, -0.1297],
        [ 2.1579,  0.6827,  1.7401,  1.4427]])


In [51]:
# matrix slicing - 
print(r2[:,1])
print(r2[:,:2])
print(r2[2:3])

tensor([0.3539, 0.4688, 1.0275, 0.6827])
tensor([[ 1.2228,  0.3539],
        [ 1.7514,  0.4688],
        [-0.0456,  1.0275],
        [ 2.1579,  0.6827]])
tensor([[-0.0456,  1.0275,  3.1760, -0.1297]])
