<a href="https://colab.research.google.com/github/pooniavaibhav/pytorchBasics/blob/main/WeightInit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
layer = nn.Linear(5,5)

In [4]:
# By default it uses Xavier initialisation technique-
layer.weight.data

tensor([[ 0.4299, -0.4005, -0.1459, -0.2818, -0.1609],
        [-0.0499, -0.0715, -0.3812,  0.0726, -0.4431],
        [ 0.1033, -0.3907, -0.2385, -0.3761,  0.4164],
        [ 0.3319, -0.4143, -0.0059, -0.3360, -0.3042],
        [ 0.2745, -0.1078,  0.3102,  0.4362, -0.0395]])

### Uniform Distribution

In [5]:
#Here we have a uniform distribution between minimum point to maximum point.
nn.init.uniform_(layer.weight.data, a=0,b=3)

tensor([[1.0990, 1.0336, 2.0511, 1.8463, 0.5226],
        [2.7556, 2.9772, 0.5488, 1.4135, 2.3348],
        [1.5000, 0.4596, 2.3554, 1.0727, 1.7616],
        [1.9151, 2.4632, 2.9966, 2.0220, 2.9341],
        [0.0034, 0.7855, 1.0790, 2.4931, 2.7395]])

### Normal Distribution-

In [7]:
#Here we have a mean of 0 and SD of 1-
nn.init.normal_(layer.weight, mean=0.0,std=1)

Parameter containing:
tensor([[-0.3990, -2.8430,  0.2546,  0.2643,  0.4955],
        [-0.2649, -0.9660, -0.9504, -0.9416,  0.7266],
        [-0.1542,  0.6295, -0.0873, -0.7549, -0.0899],
        [ 1.5681, -0.0432, -0.4913, -1.2003,  0.1148],
        [-1.5307,  0.7774,  0.0969,  1.8497,  1.6237]], requires_grad=True)